km = int(input ("Write planned trip distance:"))
kmph = int(input ("Write average speed in kmph:"))
fuel = int(input("Write fuel usage in Litres of benzin per 100km:"))
time = int((km // kmph)*60)
lpkm = float((fuel * km)/100)
print(f"drive time is {time} minutes.")
print(f"the fuel usage is {lpkm} liters.")